name: iOS starter workflow

on:
  workflow_dispatch:

jobs:
  build:
    environment: Stage
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up ruby environment
        uses: ruby/setup-ruby@v1.138.0
        with:
          ruby-version: 3.2.1
          bundler-cache: true
      - name: Decode signing certificate into a file
        env:
          CERTIFICATE_BASE64: ${{ secrets.APPLE_CERTIFICATE }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > certificate.p12
          echo Done
      - name: 'Create env file in Biba folder'
        run: |
          cd Biba/App/
          touch .env
          echo API_ENDPOINT="https://xxx.execute-api.us-west-2.amazonaws.com" >> .env
          echo APP_KEY=${{ secrets.TAPPAY_APP_KEY }} >> .env
          cat .env
          ls -1
      - name: Access code files
        run: |
          # Now you can access your code files, for example, display the content of "Biba" file
          ls -1
     
